# Path to CA dir
ca_path: '/usr/local/share/sihkarca'
ca_path_public: '/usr/local/share/sihkar_cert'

# Remove exsisting CA
# true = remove
remove_ca_enabled: false

# CA's private key password
ca_private_key_password: "{{ vault_ca_private_key_password }}"

# Name of the CA (on cert)
ca_name: 'DevCA'
# Country 
ca_country: 'FI'
# Organization
ca_organization_name: 'Dev'

# Private key encryption cipher
# use auto value
openssl_cipher: 'auto'
