- hosts: ca
  gather_facts: true
  tasks:
    - set_fact:
        encrypted_dir: "{{ ca_path}}.crypt"
        vault_dir: "{{ ca_path }}"
        vault_passwd: "{{  vars['vault_ca_dir_encryption_password_'+inventory_hostname]  }}"
    - name: Mount the encrypted dir
      include_role: 
        name: dir_crypt
        tasks_from: mount.yml 