# This play generates private keys on the hosts and generates CSRs.
# This play also performs certify role that gets the CSR processed and certicates to the host
- hosts: all
  gather_facts: true
  tasks:
    - name: Create Server PKI
      import_role:
        name: server_pki     
    - name: Certify and puts certs to Server
      import_role:
        name: certify         