---
# Why? By adding one extra layer for projecting the private key
- set_fact:
    encrypted_dir: "{{ ca_path}}.crypt"
    vault_dir: "{{ ca_path }}"
    vault_passwd: "{{ vault_ca_dir_encryption_password }}"

- name: Lets Encrypt make encrypted directory
  include_role: 
    name: dir_crypt
    tasks_from: main.yml

- name: Create CA Directory - Main
  file:
    path: "{{ ca_path }}"
    state: 'directory'
    mode: '711'
    owner: 'root'
    group: 'root'
    recurse: 'yes'
  become: yes

- name: Create CA Directory - CSR
  file:
    path: "{{ ca_path }}/csr"
    state: 'directory'
    mode: '711'
    owner: 'root'
    group: 'root'
  become: yes

- name: Create CA Directory - Private Key
  file:
    path: "{{ ca_path }}/keys"
    state: 'directory'
    mode: '711'
    owner: 'root'
    group: 'root'
  become: yes

- name: Create CA Directory - Certificates
  file:
    path: "{{ ca_path_public }}/certificates"
    state: 'directory'
    mode: '711'
    owner: 'root'
    group: 'root'
  become: yes
