---
- name: Certify the key based on CSR using the CA
  community.crypto.x509_certificate:
    backup: 'yes'
    provider: 'ownca'
    ownca_create_authority_key_identifier: 'yes'
    ownca_create_subject_key_identifier: 'create_if_not_provided'
    ownca_digest: 'sha512'
    ownca_not_after: '+730d' 
    ownca_not_before: '+0s'
    ownca_path: "{{ ca_path_public }}/certificates/ca_{{ ca_name }}.crt"
    ownca_privatekey_passphrase: "{{ ca_private_key_password }}"
    ownca_privatekey_path: "{{ ca_path }}/keys/ca_key_pkcs8.key"
    csr_path: "{{ ca_path }}/csr/{{ inventory_hostname }}.csr"
    force: 'yes'
    select_crypto_backend: 'cryptography'
    state: 'present'  
    path: "{{ ca_path_public }}/certificates/{{ inventory_hostname }}.crt"
    mode: '655'
    owner: 'root'
    group: 'root'
  no_log: 'yes'
  become: yes
  delegate_to: "{{ hostvars['ca'].ansible_host }}"