---
- name: Generate PKCS#12 file
  community.crypto.openssl_pkcs12:
    action: export
    path: "{{ pki_path }}/{{ cert_name }}/server.p12"
    friendly_name: "{{ pki_friendly_name }}"
    privatekey_path: "{{ pki_path }}/{{ cert_name }}/server_pkcs8.key"
    certificate_path: "{{ pki_path }}/{{ cert_name }}/server.crt"
    other_certificates_parse_all: true
    other_certificates:
      - '{{ pki_path }}/{{ cert_name }}/ca.crt'
        # Since we set other_certificates_parse_all to true, all
        # certificates in the CA bundle are included and not just
        # the first one.
    state: present
    privatekey_passphrase: "{{ server_pki_private_key_password }}"
    passphrase: "{{ server_pki_private_key_password }}"
    owner: 'root'
    group: "{{ pki_user_group }}"
    mode: '650'
  become: yes
  no_log: 'yes'
  when: generate_pkcs12

#- name: Dump/Parse PKCS#12 file
#  community.crypto.openssl_pkcs12:
#    action: parse
#    src: '{{ pki_path }}/{{ cert_name }}/server.p12'
#    path: '{{ pki_path }}/{{ cert_name }}/test.pem'
#    passphrase: '{{ server_pki_private_key_password }}'
#    state: present
#  become: yes