# Path to server PKI
pki_path: '/usr/local/share/server_pki'
# Locatio of Server's CSR
csr_file: "{{ pki_path }}/csr/server.csr"


# Path to CA dir
ca_path: '/usr/local/share/sihkarca'
ca_path_public: '/usr/local/share/sihkar_cert'

# Location of Server Certs on CA
cert_file: "{{ ca_path_public }}/certificates/{{ inventory_hostname }}.crt"
ca_cert_file: "{{ ca_path_public }}/certificates/ca_{{ ca_name }}.crt"

# Temp directory location on Ansible Maste
pki_temp: '~/pki_tmp'
pki_temp_cert: '~/pki_tmp_cert'

# Group name
pki_user_group: 'pki'

# Name of the CA (on cert)
ca_name: 'DevCA'

# CA's private key password
ca_private_key_password: "{{  vars['vault_ca_private_key_password_'+hostvars['ca'].inventory_hostname]  }}"

# Server's private key password
server_pki_private_key_password: "{{  vars['vault_server_pki_private_key_password_'+inventory_hostname]  }}"

# Name on the cert)
fqdn: "{{ inventory_hostname}}.test.moon"
cert_name: '{{ fqdn }}'

# PKCE12 frindly name
pki_friendly_name: "{{ inventory_hostname }}"

# Will target server need pkcs12 formated trust store?
generate_pkcs12: true